######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 29 04:36:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
SOURCES += src/main.cc
